"""empty message

Revision ID: 730e4d5cdee7
Revises: 
Create Date: 2022-12-15 22:31:53.866076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '730e4d5cdee7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chatlog',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('send_by_user_id', sa.String(length=100), nullable=False),
    sa.Column('send_by_nickname', sa.String(length=100), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('send_time', sa.DateTime(), nullable=True),
    sa.Column('send_by_chatroom', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chatroom',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('roomname', sa.String(length=100), nullable=False),
    sa.Column('max_users', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('friendrelationship',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('friend1', sa.String(length=100), nullable=False),
    sa.Column('friend2', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('personalchatlog',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('send_by_user_id', sa.String(length=100), nullable=False),
    sa.Column('receiver', sa.String(length=100), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('send_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('room-user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user', sa.String(length=100), nullable=False),
    sa.Column('room', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=1000), nullable=False),
    sa.Column('register_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('room-user')
    op.drop_table('personalchatlog')
    op.drop_table('friendrelationship')
    op.drop_table('chatroom')
    op.drop_table('chatlog')
    # ### end Alembic commands ###
